steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/helpful-bunny/helpful-bunny-repo/broker_dev:$SHORT_SHA', '-t', 'gcr.io/helpful-bunny/helpful-bunny-repo/broker_dev:latest', '.']
    dir: 'broker'
images: ['gcr.io/helpful-bunny/helpful-bunny-repo/broker_dev']
