steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/helpful-bunny/helpful-bunny-repo/web_dev:$SHORT_SHA', '-t', 'gcr.io/helpful-bunny/helpful-bunny-repo/web_dev:latest', '.']
    dir: 'web'
images: ['gcr.io/helpful-bunny/helpful-bunny-repo/web_dev']